### ISSUE TITLE
Allow /tmp and /var to be on different partitions - invalid cross-device link

### ISSUE THREAD

**Issue by YBonline** [uhppoted/uhppoted-httpd#20]
My system is setup with /var on its own partition, along with /tmp being a tmpfs

Whenever trying to use uhppoted-httpd when it tries to write to the files, it always gives a rename <filename>: invalid cross-device link error

My understand is you need to use move instead of rename to account for them being separate partitions.

**Comment by uhppoted** [comment]
Huh! In theory Go [`Rename`](https://pkg.go.dev/os#Rename) is supposed to do a move:

> Rename renames (moves) oldpath to newpath. If newpath already exists and is not a directory, Rename replaces it. OS-specific restrictions may apply when oldpath and newpath are in different directories. Even within the same directory, on non-Unix platforms Rename is not an atomic operation. 

I wonder if they tested it on a _tmpfs_ .. ok, let me look into it.

**Comment by YBonline** [comment]
https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link

os.rename only works if source and destination are on the same file system. You should use shutil.move instead.

At least according to my googling

**Comment by uhppoted** [comment]
Seems to be an open issue in Go: [#41487  os: if rename system call fails, try ioctl(FICLONE)](https://github.com/golang/go/issues/41487).

Hmm, I use `os.Rename` **everywhere** ... ok, am going to have to figure out a nice way to do it.

**Comment by uhppoted** [comment]
Hi,

Well, that was minor can of worms :-) ..  however, FWIW, there's a provisional fix for this issue in the _main_ branch which:

1. First attempts to do a _rename_
2. If the _rename_ fails then attempts to do a _file copy and delete_

The actual change turned out to be fairly small and relatively low impact - I've tested it briefly and it behaves as expected. 

If you would like to try it out you'll have to clone the repo and build it locally. Which is reasonably straightforward - the instructions are in the README ([Building from source](https://github.com/uhppoted/uhppoted-httpd#building-from-source)) but if it's problem let me know and I can put up a nightly build on _github_.

_Note_: the current implementation can potentially leave a temporary file in place if the machine crashes while copying the file. Hopefully this should be rare enough not to be an immediate problem while I work on cleaning up temporary files on startup.

**Comment by uhppoted** [comment]
Ok, _uhppoted-httpd_ should be good to go. 

NTS: also update:
- [  ] uhppoted-app-db
- [  ] uhppoted-app-sheets
- [  ] uhppoted-app-wild-apricot
- [  ] uhppoted-codegen
- [  ]uhppoted-lib:eventlog
- [  ] uhppoted-lib:listen
- [  ] uhppoted-lib:kvs

**Comment by uhppoted** [comment]
And that's a wrap .. will leave this open for a couple of days in case something weird turns up.

**Comment by uhppoted** [comment]
Closing this - seems to be ok so far. Feel free to reopen if you run into anything.
