### ISSUE TITLE
[Enhancement] Cards | provide explanation for why row is in errored state

### ISSUE THREAD

**Issue by iKrushYou** [uhppoted/uhppoted-httpd#35]
<img width="797" alt="image" src="https://github.com/uhppoted/uhppoted-httpd/assets/1500721/db6d80f9-8cec-429e-806b-5a54acdb286e">

I finally got a card added (with the correct from / to dates) and it is still in the red errored state. Is there anywhere to find out why this is still marked as errored?

**Comment by uhppoted** [comment]
A 'red' row means the card permissions/dates do not match the record on the controllers i.e. the record has been changed externally by somebody (possibly for good reason) since it was last downloaded to the controller.

There is a _Synchronize ACL_ command under the _admin_ menu if you want to force update the controllers - but it will replace all cards on the controllers which may not be what you want  if you are just testing.

**Comment by iKrushYou** [comment]
thanks @uhppoted I think that this might be erroring because my server keeps timing out - https://github.com/uhppoted/uhppoted-httpd/issues/36

**Comment by uhppoted** [comment]
Makes sense to me! As per https://github.com/uhppoted/uhppoted-httpd/issues/36, am going to close this, but feel free to reopen if it becomes apparent that there is more to it than a network connectivity issue.
